# Generated by Django 6.0.1 on 2026-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Video')),
                ('descripcion', models.TextField(verbose_name='Párrafo Informativo')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Archivo de Video')),
                ('anio', models.CharField(choices=[('2', 'Segundo Año'), ('4', 'Cuarto Año')], max_length=10, verbose_name='Año Escolar')),
            ],
        ),
    ]
