# Generated by Django 6.0.6 on 2026-06-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoaudiovisual',
            name='video',
        ),
        migrations.AddField(
            model_name='contenidoaudiovisual',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='guia_fotos/', verbose_name='Imagen Explicativa'),
        ),
        migrations.AddField(
            model_name='contenidoaudiovisual',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Youtube'),
        ),
    ]
