# Generated by Django 6.0.6 on 2026-06-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_remove_contenidoaudiovisual_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoaudiovisual',
            name='imagen',
        ),
    ]
